// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/BusyPeopleAPZ/APZ-3/server/vms"
)

// Injectors from module.go:

func ComposeApiServer(port HttpPortNumber) (*VMSApiServer, error) {
	pool, err := DatabaseConnection()
	if err != nil {
		return nil, err
	}
	container := vms.CreateContainer(pool)
	handlerFunc := vms.MainLoader(container)
	vmsApiServer := &VMSApiServer{
		Port:       port,
		VMSHandler: handlerFunc,
	}
	return vmsApiServer, nil
}
